### ISSUE TITLE
Add precision parameter to all functions/Add precision to the final calculation

### ISSUE THREAD

**Issue by gabrieltalih** [Flyinchicken/Comp-354-Team-N#22]
Refers: #14

**Comment by sunys1** [comment]
@Devansh-Vaidya @gabrieltalih Instead of passing the precision as a parameter to all functions, maybe it's simpler to store it as a global variable in main.js and apply it in inputProcessing().

**Comment by sunys1** [comment]
The precision feature has been taken care of in another ticket. We will close this one.
